ARG OS=ubuntu
ARG VERSION=18.04

FROM ${OS}:${VERSION}

VOLUME /etc/rfc7030-client

RUN apt-get update \
    && apt-get install -y \
          build-essential \
          cmake \
          libssl-dev \
          libcurl4-openssl-dev \
          pkg-config \
          git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /etc/rfc7030-client

CMD ["./build.sh"]

