---
name: General Discussion
about: Start a general discussion
title: '[DISCUSSION] '
labels: ['discussion']
assignees: ''
---

## Topic
Brief description of what you'd like to discuss.

## Context
Provide any relevant context or background information.

## Questions/Points for Discussion
- [ ] Point 1
- [ ] Point 2
- [ ] Point 3

## Additional Information
Any other information that might be helpful.
