---
name: Showcase
about: Show off your project using this EST client
title: '[SHOWCASE] '
labels: ['showcase']
assignees: ''
---

## Project Overview
Brief description of your project.

## How you're using the EST client
Describe how you're using this EST client in your project.

## Key Features
What are the main features of your implementation?

## Screenshots/Demo
If applicable, include screenshots or demo links.

## Code Example
Share relevant code snippets (if you're comfortable doing so).

## Lessons Learned
What challenges did you face and how did you solve them?

## Future Plans
What are your future plans for this project?
