#!/bin/bash
# Pre-removal script for rfc7030-est-client

set -e

# Remove symlink
if [ -L /usr/bin/rfc7030-est-client ]; then
    rm -f /usr/bin/rfc7030-est-client
fi

echo "rfc7030-est-client removed successfully"
