name: Ubuntu Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
            
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libssl-dev \
          libcurl4-openssl-dev \
          pkg-config
        
    - name: Configure CMake
      run: |
        cmake -Ssrc -Bbuild \
          -DBUILD_CLONE_SUBMODULES=ON \
          -DUSE_OPENSSL=ON
          
    - name: Build project
      run: |
        cd build
        make -j$(nproc)
        
    - name: Run unit tests
      run: |
        cd build
        ./bin/rfc7030-est-client-tests
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-ubuntu
        path: build/
        retention-days: 30
