name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libssl-dev \
          libcurl4-openssl-dev \
          pkg-config \
          git
          
    - name: Configure CMake
      run: |
        cmake -Ssrc -Bbuild \
          -DBUILD_CLONE_SUBMODULES=ON \
          -DUSE_OPENSSL=ON \
          -DCMAKE_BUILD_TYPE=Release
          
    - name: Build project
      run: |
        cd build
        make -j$(nproc)
        
    - name: Run tests
      run: |
        cd build
        ./bin/rfc7030-est-client-tests
        
    - name: Create release archive
      run: |
        mkdir -p release
        cp -r build/bin release/
        cp -r test release/
        cp README.md release/
        cp LICENSE release/
        tar -czf rfc7030-est-client-${GITHUB_REF_NAME}.tar.gz -C release .
        
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.upload_url }}
        asset_path: ./rfc7030-est-client-${GITHUB_REF_NAME}.tar.gz
        asset_name: rfc7030-est-client-${GITHUB_REF_NAME}.tar.gz
        asset_content_type: application/gzip
