name: CI/CD Pipeline

on:
  push:
    tags: 
    - 'v*.*.*'

jobs:
  src:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive
        
    - name: Create source code asset
      run: |
        zip -r rfc7030-est-client-${GITHUB_REF_NAME}-src.zip src test AUTHORS README.md LICENSE
        tar -czf rfc7030-est-client-${GITHUB_REF_NAME}-src.tar.gz src test AUTHORS README.md LICENSE

    - name: Upload File zip
      uses: actions/upload-artifact@v4
      with:
        name: zip-src
        path: rfc7030-est-client-${GITHUB_REF_NAME}-src.zip
        retention-days: 1

    - name: Upload File tar.gz
      uses: actions/upload-artifact@v4
      with:
        name: tar-src
        path: rfc7030-est-client-${GITHUB_REF_NAME}-src.tar.gz
        retention-days: 1

  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: debian11
      run: |
        build.debian11.sh
    - name: debian12
      run: |
        build.debian12.sh
    - name: ubuntu1804
      run: |
        build.ubuntu18.04.sh
    - name: ubuntu2004
      run: |
        build.ubuntu20.04.sh
    - name: ubuntu2204
      run: |
        build.ubuntu22.04.sh
    - name: Zip artifacts
      run: |
        zip -r dist.zip dist

    - name: Upload File zip
      uses: actions/upload-artifact@v4
      with:
        name: dist.zip
        path: dist.zip
        retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: 
    - build
    - src

    steps:
    - name: Download artifact zip src
      uses: actions/download-artifact@v4
      with:
        name: zip-src
        path: ./rfc7030-est-client-${GITHUB_REF_NAME}-src.zip

    - name: Download artifact tar src
      uses: actions/download-artifact@v4
      with:
        name: tar-src
        path: ./rfc7030-est-client-${GITHUB_REF_NAME}-src.tar

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist.zip
        path: ./dist.zip

    - name: Explode build artifacts
      run: |
        unzip dist.zip -d ./dist
        zip -r rfc7030-est-client-${GITHUB_REF_NAME}.ubuntu-18.04.zip ./dist/ubuntu1804
        tar -czf rfc7030-est-client-${GITHUB_REF_NAME}.ubuntu-18.04.tar.gz ./dist/ubuntu1804
        zip -r rfc7030-est-client-${GITHUB_REF_NAME}.ubuntu-20.04.zip ./dist/ubuntu2004
        tar -czf rfc7030-est-client-${GITHUB_REF_NAME}.ubuntu-20.04.tar.gz ./dist/ubuntu2004
        zip -r rfc7030-est-client-${GITHUB_REF_NAME}.ubuntu-22.04.zip ./dist/ubuntu2204
        tar -czf rfc7030-est-client-${GITHUB_REF_NAME}.ubuntu-22.04.tar.gz ./dist/ubuntu2204
        zip -r rfc7030-est-client-${GITHUB_REF_NAME}.debian-11.zip ./dist/debian11
        tar -czf rfc7030-est-client-${GITHUB_REF_NAME}.debian-11.tar.gz ./dist/debian11
        zip -r rfc7030-est-client-${GITHUB_REF_NAME}.debian-12.zip ./dist/debian12
        tar -czf rfc7030-est-client-${GITHUB_REF_NAME}.debian-12.tar.gz ./dist/debian12 

    - name: Release
      uses: softprops/action-gh-release@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ./rfc7030-est-client-${GITHUB_REF_NAME}-src.zip
          ./rfc7030-est-client-${GITHUB_REF_NAME}-src.tar.gz
          ./rfc7030-est-client-${GITHUB_REF_NAME}.ubuntu-18.04.zip
          ./rfc7030-est-client-${GITHUB_REF_NAME}.ubuntu-18.04.tar.gz
          ./rfc7030-est-client-${GITHUB_REF_NAME}.ubuntu-20.04.zip
          ./rfc7030-est-client-${GITHUB_REF_NAME}.ubuntu-20.04.tar.gz
          ./rfc7030-est-client-${GITHUB_REF_NAME}.ubuntu-22.04.zip
          ./rfc7030-est-client-${GITHUB_REF_NAME}.ubuntu-22.04.tar.gz
          ./rfc7030-est-client-${GITHUB_REF_NAME}.debian-11.zip
          ./rfc7030-est-client-${GITHUB_REF_NAME}.debian-11.tar.gz
          ./rfc7030-est-client-${GITHUB_REF_NAME}.debian-12.zip
          ./rfc7030-est-client-${GITHUB_REF_NAME}.debian-12.tar.gz

