name: Release

on:
  push:
    tags: 
    - '*.*.*'

jobs:
  build-debian11:
    uses: ./.github/workflows/compile.yml
    with:
      type: apt
      os: debian
      version: '11'
      name: rfc7030-est-client-debian11

  build-debian12:
    uses: ./.github/workflows/compile.yml
    with:
      type: apt
      os: debian
      version: '12'
      name: rfc7030-est-client-debian12

  build-ubuntu2004:
    uses: ./.github/workflows/compile.yml
    with:
      type: apt
      os: ubuntu
      version: '20.04'  
      name: rfc7030-est-client-ubuntu2004

  build-ubuntu2204:
    uses: ./.github/workflows/compile.yml
    with:
      type: apt
      os: ubuntu
      version: '22.04'
      name: rfc7030-est-client-ubuntu2204

  build-ubuntu2404:
    uses: ./.github/workflows/compile.yml
    with:
      type: apt
      os: ubuntu
      version: '24.04'
      name: rfc7030-est-client-ubuntu2404

  release:
    runs-on: ubuntu-latest
    needs: 
    - build-debian11
    - build-debian12
    - build-ubuntu2004
    - build-ubuntu2204
    - build-ubuntu2404

    steps:
    - name: Download deb11
      uses: actions/download-artifact@v5
      with:
        name: rfc7030-est-client.debian11

    - name: Download deb11 pkg
      uses: actions/download-artifact@v5
      with:
        name: rfc7030-est-client.debian11.deb

    - name: Download deb12
      uses: actions/download-artifact@v5
      with:
        name: rfc7030-est-client.debian12

    - name: Download deb12 pkg
      uses: actions/download-artifact@v5
      with:
        name: rfc7030-est-client.debian12.deb

    - name: Download ub2004
      uses: actions/download-artifact@v5
      with:
        name: rfc7030-est-client.ubuntu2004

    - name: Download ub2004 pkg
      uses: actions/download-artifact@v5
      with:
        name: rfc7030-est-client.ubuntu20.04.deb

    - name: Download ub2204
      uses: actions/download-artifact@v5
      with:
        name: rfc7030-est-client.ubuntu22.04 

    - name: Download ub2204 pkg
      uses: actions/download-artifact@v5
      with:
        name: rfc7030-est-client.ubuntu22.04.deb 

    - name: Download ub2404
      uses: actions/download-artifact@v5
      with:
        name: rfc7030-est-client.ubuntu24.04

    - name: Download ub2404 pkg
      uses: actions/download-artifact@v5
      with:
        name: rfc7030-est-client.ubuntu24.04.deb

    - name: Release
      uses: softprops/action-gh-release@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ github.ref_name }}
        files: |
          ./rfc7030-est-client.debian11.deb
          ./rfc7030-est-client.debian12.deb
          ./rfc7030-est-client.ubuntu20.04.deb
          ./rfc7030-est-client.ubuntu22.04.deb
          ./rfc7030-est-client.ubuntu24.04.deb
          ./rfc7030-est-client.debian11
          ./rfc7030-est-client.debian12
          ./rfc7030-est-client.ubuntu20.04
          ./rfc7030-est-client.ubuntu22.04
          ./rfc7030-est-client.ubuntu24.04

