name: CI/CD Pipeline

on:
  push:
    tags: 
    - 'v*.*.*'

jobs:
  src:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive
        
    - name: Create source code asset
      run: |
        zip -r rfc7030-est-client-src.zip src test AUTHORS README.md LICENSE
        tar -czf rfc7030-est-client-src.tar.gz src test AUTHORS README.md LICENSE

    - name: Upload source code
      uses: actions/upload-artifact@v4
      with:
        name: code
        path: |
          src
          test
          AUTHORS
          README.md
          LICENSE
        retention-days: 1

  build-debian11:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: debian11
      run: |
        ./build.debian11.sh
    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: debian11
        path: dist
        retention-days: 1

  build-debian12:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: debian12
      run: |
        ./build.debian12.sh
    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: debian12
        path: dist
        retention-days: 1

  build-ubuntu2004:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: ubuntu2004
      run: |
        ./build.ubuntu20.04.sh
    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu2004
        path: dist
        retention-days: 1

  build-ubuntu2204:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: ubuntu2204
      run: |
        ./build.ubuntu22.04.sh
    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu2204
        path: dist
        retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: 
    - build-debian11
    - build-debian12
    - build-ubuntu2004
    - build-ubuntu2204
    - src

    steps:
    - name: Download code
      uses: actions/download-artifact@v4
      with:
        name: code

    - name: Download deb11
      uses: actions/download-artifact@v4
      with:
        name: debian11

    - name: Download deb12
      uses: actions/download-artifact@v4
      with:
        name: debian12

    - name: Download ub2004
      uses: actions/download-artifact@v4
      with:
        name: ubuntu2004

    - name: Download ub2204
      uses: actions/download-artifact@v4
      with:
        name: ubuntu2204

    - name:
      run: ls -la

    - name: Explode build artifacts
      run: |
        zip -r rfc7030-est-client-src.zip src test AUTHORS README.md LICENSE
        tar -czf rfc7030-est-client-src.tar.gz src test AUTHORS README.md LICENSE
        zip -r rfc7030-est-client.ubuntu-20.04.zip ./ubuntu2004
        tar -czf rfc7030-est-client.ubuntu-20.04.tar.gz ./ubuntu2004
        zip -r rfc7030-est-client.ubuntu-22.04.zip ./ubuntu2204
        tar -czf rfc7030-est-client.ubuntu-22.04.tar.gz ./ubuntu2204
        zip -r rfc7030-est-client.debian-11.zip ./debian11
        tar -czf rfc7030-est-client.debian-11.tar.gz ./debian11
        zip -r rfc7030-est-client.debian-12.zip ./debian12
        tar -czf rfc7030-est-client.debian-12.tar.gz ./debian12 

    - name: Release
      uses: softprops/action-gh-release@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ github.ref_name }}
        files: |
          ./rfc7030-est-client-src.zip
          ./rfc7030-est-client-src.tar.gz
          ./rfc7030-est-client.ubuntu-20.04.zip
          ./rfc7030-est-client.ubuntu-20.04.tar.gz
          ./rfc7030-est-client.ubuntu-22.04.zip
          ./rfc7030-est-client.ubuntu-22.04.tar.gz
          ./rfc7030-est-client.debian-11.zip
          ./rfc7030-est-client.debian-11.tar.gz
          ./rfc7030-est-client.debian-12.zip
          ./rfc7030-est-client.debian-12.tar.gz

