name: CI/CD Pipeline

on:
  push:
    tags: 
    - 'v*.*.*'

jobs:
  src:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive
        
    - name: Create source code asset
      run: |
        zip -r rfc7030-est-client-src.zip src test AUTHORS README.md LICENSE
        tar -czf rfc7030-est-client-src.tar.gz src test AUTHORS README.md LICENSE

    - name: Upload source code
      uses: actions/upload-artifact@v4
      with:
        name: code
        path: |
          src
          test
          AUTHORS
          README.md
          LICENSE
        retention-days: 1

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: debian11
      run: |
        ./build.debian11.sh
    - name: debian12
      run: |
        ./build.debian12.sh
    - name: ubuntu2004
      run: |
        ./build.ubuntu20.04.sh
    - name: ubuntu2204
      run: |
        ./build.ubuntu22.04.sh
    - name: Zip artifacts
      run: |
        zip -r dist.zip dist

    - name: Upload File zip
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
        retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: 
    - build
    - src

    steps:
    - name: Download artifact zip src
      uses: actions/download-artifact@v4
      with:
        name: code

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist

    - name:
      run: ls -la

    - name: Explode build artifacts
      run: |
        zip -r rfc7030-est-client-src.zip src test AUTHORS README.md LICENSE
        tar -czf rfc7030-est-client-src.tar.gz src test AUTHORS README.md LICENSE
        zip -r rfc7030-est-client.ubuntu-20.04.zip ./dist/ubuntu2004
        tar -czf rfc7030-est-client.ubuntu-20.04.tar.gz ./dist/ubuntu2004
        zip -r rfc7030-est-client.ubuntu-22.04.zip ./dist/ubuntu2204
        tar -czf rfc7030-est-client.ubuntu-22.04.tar.gz ./dist/ubuntu2204
        zip -r rfc7030-est-client.debian-11.zip ./dist/debian11
        tar -czf rfc7030-est-client.debian-11.tar.gz ./dist/debian11
        zip -r rfc7030-est-client.debian-12.zip ./dist/debian12
        tar -czf rfc7030-est-client.debian-12.tar.gz ./dist/debian12 

    - name: Release
      uses: softprops/action-gh-release@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ github.ref_name }}
        files: |
          ./rfc7030-est-client-src.zip
          ./rfc7030-est-client-src.tar.gz
          ./rfc7030-est-client.ubuntu-20.04.zip
          ./rfc7030-est-client.ubuntu-20.04.tar.gz
          ./rfc7030-est-client.ubuntu-22.04.zip
          ./rfc7030-est-client.ubuntu-22.04.tar.gz
          ./rfc7030-est-client.debian-11.zip
          ./rfc7030-est-client.debian-11.tar.gz
          ./rfc7030-est-client.debian-12.zip
          ./rfc7030-est-client.debian-12.tar.gz

